### ISSUE TITLE
User can See the car 

### ISSUE THREAD

**Issue by KennethDelaCruz** [KennethDelaCruz/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a background, in which the car will be contained in
- [x] Create the Car within the background 
- [x] Add any necessary styling to both the car and background(height, width, background color)
