### ISSUE TITLE
User can Steer the car

### ISSUE THREAD

**Issue by KennethDelaCruz** [KennethDelaCruz/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Add an eventListener to the window, listening to any 'keydown' input for  'Left' 'Right' input from the arrow keys
- [x] Let the eventListener rotate the car by using css styling. depending on the input that was give (right turns the car right, left turns the car left. etc etc.)
- [x] Create an 'index' to determine which way the car is facing. (0,1, 2, 3) and add it to the created Data Model
- [x] Create a variable that will increase incrementally when 'right' is pressed or decrease incrementally 'left' is pressed.
- [x] Multiply the new variable to a variable that would multiply it by 90, to create the degrees that the image needs to rotate
- [x] apply that variable to the `Car` css styling
