### ISSUE TITLE
You can start the car

### ISSUE THREAD

**Issue by KennethDelaCruz** [KennethDelaCruz/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [ ] Add styling to the car that would give the car `position:absolute`
- [ ] Add a location to your data model to hold the car's 'x' and 'y' coordinates on the page.
- [ ] Create an eventListener on window, to listen for input of 'spacebar'. CONSOLE LOG TO CHECK
- [ ] create a function that would move the vehicle a few pixels every 16miliseconds when the space bar is pressed. depending on where the car is facing. 
- [ ] Update the coordinates to the data modal according to the position of the car. Console.log to see if is being saved properly
- [ ] Create an 'var' with a boolean for when the car is "started" and when the car is idle. This will determine whether or not the car is moving or not.
